#!/usr/bin/env python3
"""
generate.py — generate a satellite image from a text prompt with FlowSat.

The simplest possible entry point. Give it a prompt, get a PNG:

    python generate.py --prompt "An airport with a long grey runway."

Metadata (location, resolution, date, cloud cover) has sensible defaults, so
you do not have to think about it to get started. When you do want to control
it, every field is a flag:

    python generate.py \
        --prompt "A farmland with irrigated green fields." \
        --lat 45.0 --lon 5.0 --month 7 --gsd 0.5

Runs on GPU if one is available and on CPU otherwise (slower, but it works —
about a minute per image on a modern laptop CPU).

--------------------------------------------------------------------------
WRITING GOOD PROMPTS
--------------------------------------------------------------------------
FlowSat was trained mostly on dense, descriptive captions (100-200 words)
generated by a vision-language model, mixed with short captions and some
caption-free samples. Both styles work, but they behave differently:

  short   "An airport."
          Underspecified. The model fills in the rest, and the metadata has
          more influence over the result.

  rich    "Warm tan and ochre tones over dry farmland. A long grey paved
           runway crosses the lower third, flanked by low rectangular
           hangars and an apron with parked aircraft to the right."
          Detailed. Follows your description closely. Best image quality.

  none    ""
          Pure metadata-conditioned generation.

If output quality disappoints, lengthen the prompt before changing anything
else — describe the palette, the terrain, the structures and where they sit.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch
from PIL import Image
from PIL.PngImagePlugin import PngInfo


# ---------------------------------------------------------------------------
# Metadata
#
# FlowSat conditions on seven acquisition fields, each normalised to ~[0, 1000]:
#   longitude, latitude, ground sample distance, cloud cover, year, month, day
# The defaults below are a neutral, in-distribution acquisition.
# ---------------------------------------------------------------------------

DEFAULTS = dict(lon=5.0, lat=45.0, gsd=0.5, cloud=0.0, year=2016, month=7, day=15)


def build_metadata(lon, lat, gsd, cloud, year, month, day, max_gsd=1.0):
    md = [(lon + 180.0) / 360.0 * 1000.0,
          (lat + 90.0) / 180.0 * 1000.0,
          gsd / max_gsd * 1000.0,
          (cloud / 100.0) * 1000.0,
          (year - 1980.0) / 120.0 * 1000.0,
          month / 12.0 * 1000.0,
          day / 31.0 * 1000.0]
    names = ["longitude", "latitude", "gsd", "cloud", "year", "month", "day"]
    for n, v in zip(names, md):
        if v < -1e-6 or v > 1000.0 + 1e-6:
            print(f"[warn] {n} normalises to {v:.0f}, outside the trained range "
                  f"[0, 1000]. Output may degrade. "
                  f"{'Is --gsd larger than --max-gsd?' if n == 'gsd' else ''}")
    return md


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

def load_model(ckpt, pretrained, device, dtype, use_satclip=True):
    """Build FlowSat and load a checkpoint.

    NOTE: load_pretrained=True is required. It makes the architecture come from
    the real Sana config; building from the manual config instead produces a
    slightly different network, and `strict=False` would then silently discard
    the mismatched checkpoint tensors, leaving randomly-initialised weights and
    nonsense images. The guard below turns that failure into an error.
    """
    try:
        from flowsat.models.sat_sana import SatSana
    except ImportError:
        sys.exit("[error] cannot import flowsat — install with `pip install -e .` "
                 "or run from the repository root.")
    from diffusers import AutoencoderDC
    from transformers import AutoTokenizer, AutoModel

    print(f"[1/3] loading text encoder + VAE  ({pretrained})")
    tok = AutoTokenizer.from_pretrained(pretrained, subfolder="tokenizer")
    txt = AutoModel.from_pretrained(pretrained, subfolder="text_encoder",
                                    attn_implementation="eager")
    vae = AutoencoderDC.from_pretrained(pretrained, subfolder="vae")
    txt.requires_grad_(False); vae.requires_grad_(False)
    txt = txt.to(device, torch.float32).eval()
    vae = vae.to(device, dtype).eval()

    hidden = getattr(txt.config, "hidden_size", getattr(txt.config, "d_model", 2304))

    print("[2/3] building FlowSat backbone")
    model = SatSana(latent_size=512 // 32, in_channels=vae.config.latent_channels,
                    num_metadata=7, use_metadata=True, cross_attention_dim=hidden,
                    pretrained_sana_id=pretrained, load_pretrained=True)
    if use_satclip:
        from flowsat.models.sat_clip import SatCLIPMetadataEncoder
        model.set_metadata_encoder(
            SatCLIPMetadataEncoder(embed_dim=model.embed_dim, num_metadata=7))

    print(f"[3/3] loading weights            ({ckpt})")
    ck = Path(ckpt)
    wf = next((ck / n for n in ("model_0.pt", "model.pt", "pytorch_model.bin",
                                "diffusion_pytorch_model.bin")
               if (ck / n).exists()), ck if ck.is_file() else None)
    if wf is None:
        sys.exit(f"[error] no weight file found in {ck}")
    sd = torch.load(wf, map_location="cpu", weights_only=True)
    sd = sd.get("state_dict", sd)
    sd = {k[7:] if k.startswith("module.") else k: v for k, v in sd.items()}
    missing, unexpected = model.load_state_dict(sd, strict=False)
    if len(missing) > 5 or len(unexpected) > 5:
        print(f"      missing[:5]    = {missing[:5]}")
        print(f"      unexpected[:5] = {unexpected[:5]}")
        sys.exit(
            f"[error] checkpoint did not load cleanly ({len(missing)} missing, "
            f"{len(unexpected)} unexpected keys).\n"
            f"        This is an architecture mismatch — the generated images "
            f"would come from partly random weights.\n"
            f"        Check that --pretrained points at the same Sana snapshot "
            f"used for training, and pass --no-satclip if the checkpoint was "
            f"trained without the SatCLIP metadata encoder.")

    return model.to(device, dtype).eval(), vae, tok, txt


# ---------------------------------------------------------------------------
# Sampling
# ---------------------------------------------------------------------------

@torch.no_grad()
def generate(model, vae, tok, txt, prompt, metadata, *, seed, steps, guidance,
             resolution, max_len, device, dtype):
    from flowsat.flow.flow_sampler import EulerSampler

    def encode(text):
        t = tok(text, padding="max_length", max_length=max_len,
                truncation=True, return_tensors="pt")
        ids = t.input_ids.to(device)
        mask = (ids != tok.pad_token_id).long()
        empty = mask.sum(1) == 0
        if empty.any():                    # all-pad rows break the attention softmax
            mask[empty, 0] = 1
        return txt(ids, attention_mask=mask)[0], mask

    n_tok = len(tok(prompt, truncation=False).input_ids) if prompt else 0
    if n_tok > max_len:
        print(f"[warn] prompt is {n_tok} tokens and will be truncated to "
              f"{max_len}. Raise --max-len to keep all of it.")

    cond_e, cond_m = encode(prompt)
    unc_e, unc_m = encode("")
    emb = torch.cat([unc_e, cond_e], 0).to(dtype)
    mask = torch.cat([unc_m, cond_m], 0)

    # Real metadata goes to BOTH classifier-free-guidance branches; only the
    # text direction is guided. A zero metadata vector would be out of
    # distribution (normalised zero means lon=-180, lat=-90, year=1980).
    md = torch.tensor([metadata], device=device, dtype=dtype)
    md2 = torch.cat([md, md], 0)

    g = torch.Generator(device=device).manual_seed(seed)
    ls = resolution // 32
    z = torch.randn(1, vae.config.latent_channels, ls, ls,
                    device=device, dtype=dtype, generator=g)

    def velocity(x_t, t, **_):
        v = model(torch.cat([x_t, x_t], 0), torch.cat([t, t], 0),
                  encoder_hidden_states=emb, metadata=md2,
                  attention_mask=mask).sample
        v_uncond, v_cond = v.chunk(2, 0)
        return v_uncond + guidance * (v_cond - v_uncond)

    latents = EulerSampler(num_steps=steps).sample(
        velocity, z, num_steps=steps, show_progress=True)
    img = (vae.decode(latents / vae.config.scaling_factor).sample / 2 + 0.5).clamp(0, 1)
    arr = (img[0].float().cpu().permute(1, 2, 0).numpy() * 255).astype("uint8")
    return Image.fromarray(arr)


# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        description="Generate a satellite image with FlowSat.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("WRITING GOOD PROMPTS")[1])

    p.add_argument("--prompt", required=True, help="text description of the scene")
    p.add_argument("--out", default="output.png")
    p.add_argument("--ckpt", default="checkpoints/flowsat-fmow-512",
                   help="FlowSat checkpoint directory")
    p.add_argument("--pretrained",
                   default="Efficient-Large-Model/Sana_600M_512px_diffusers",
                   help="Sana snapshot providing the VAE, tokenizer and text encoder")

    g = p.add_argument_group("metadata (all optional)")
    g.add_argument("--lat", type=float, default=DEFAULTS["lat"], help="-90 to 90")
    g.add_argument("--lon", type=float, default=DEFAULTS["lon"], help="-180 to 180")
    g.add_argument("--gsd", type=float, default=DEFAULTS["gsd"],
                   help="ground sample distance, metres per pixel")
    g.add_argument("--cloud", type=float, default=DEFAULTS["cloud"],
                   help="cloud cover percentage, 0-100")
    g.add_argument("--year", type=int, default=DEFAULTS["year"])
    g.add_argument("--month", type=int, default=DEFAULTS["month"], help="1-12")
    g.add_argument("--day", type=int, default=DEFAULTS["day"], help="1-31")
    g.add_argument("--max-gsd", type=float, default=1.0,
                   help="GSD normalisation constant; must match training")

    s = p.add_argument_group("sampling")
    s.add_argument("--seed", type=int, default=42)
    s.add_argument("--steps", type=int, default=20,
                   help="Euler steps; 20 is the trained operating point")
    s.add_argument("--guidance", type=float, default=2.5,
                   help="classifier-free guidance on the text direction")
    s.add_argument("--resolution", type=int, default=512)
    s.add_argument("--max-len", type=int, default=120,
                   help="caption token limit; must match the checkpoint")
    s.add_argument("--n", type=int, default=1, help="number of images (seed +1 each)")

    p.add_argument("--device", default="auto", choices=["auto", "cuda", "cpu"])
    p.add_argument("--no-satclip", action="store_true",
                   help="checkpoint was trained without the SatCLIP encoder")
    args = p.parse_args()

    if args.device == "auto":
        dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        dev = torch.device(args.device)
    dtype = torch.bfloat16 if dev.type == "cuda" else torch.float32
    if dev.type == "cpu":
        print("[info] running on CPU — expect roughly a minute per image.")

    model, vae, tok, txt = load_model(args.ckpt, args.pretrained, dev, dtype,
                                      use_satclip=not args.no_satclip)
    tok.model_max_length = args.max_len

    md = build_metadata(args.lon, args.lat, args.gsd, args.cloud,
                        args.year, args.month, args.day, args.max_gsd)
    print(f"\nprompt   : {args.prompt}")
    print(f"metadata : lat {args.lat}, lon {args.lon}, {args.gsd} m/px, "
          f"{args.cloud:.0f}% cloud, {args.year}-{args.month:02d}-{args.day:02d}\n")

    out = Path(args.out)
    for i in range(args.n):
        seed = args.seed + i
        img = generate(model, vae, tok, txt, args.prompt, md,
                       seed=seed, steps=args.steps, guidance=args.guidance,
                       resolution=args.resolution, max_len=args.max_len,
                       device=dev, dtype=dtype)
        path = out if args.n == 1 else out.with_name(f"{out.stem}_{seed}{out.suffix}")
        info = PngInfo()
        info.add_text("prompt", args.prompt)
        info.add_text("metadata", f"lat={args.lat} lon={args.lon} gsd={args.gsd} "
                                  f"cloud={args.cloud} "
                                  f"date={args.year}-{args.month:02d}-{args.day:02d}")
        info.add_text("seed", str(seed))
        info.add_text("steps", str(args.steps))
        info.add_text("guidance", str(args.guidance))
        path.parent.mkdir(parents=True, exist_ok=True)
        img.save(path, pnginfo=info)
        print(f"saved {path}")

    print("\nGeneration settings are stored in the PNG metadata: "
          "Image.open(path).text")


if __name__ == "__main__":
    main()
